docs/deploy/09-aks-cluster.md

When I changed the variable name for the cert to have the `_BASE64` suffix, I missed a spot. :(  Thanks @magrande for finding that!

sync missed env variable name

---

docs/additional-considerations.md
docs/deploy/04-subscription.md
docs/deploy/14-cleanup.md
subscription.json

Because network watcher is not a workload concern, including it can be problematic. However having it in place is important for regulated workloads.  Found some middle ground here.  When NO network watchers are detected, then deploy a strong foundation that will include them.  If _any_ are detected, even those from prior runs of this, then simply deploy as we do before this change.
This way some customers get benefit, and those that already have Network Watcher in place, likely already have a strategy around it and don't need us stepping on it.

Add network watcher enablement when safe

---

cluster-stamp.json
cluster-stamp.v2.json
networking/hub-region.v2.json

* Update to AKS 1.21.2 (from 1.21.1)
* Remove the node pool firewall allocation for NTP
* revert back to ntp.ubuntu.com for firewall rule

Update to AKS 1.21.2 and reduce NTP firewall rule

---

cluster-stamp.json
cluster-stamp.v2.json
docs/deploy/01-prerequisites.md
docs/deploy/05-networking-hub.md

* Be explicit about no public DNS record for the private cluster
* Updated the Cloud Shell button to be the latest and force that the user starts in BASH not PowerShell (feedback from hackathon)
* Minor wording update to remove possible confusion around IP address conflicts

Force disable public DNS for Private Cluster

---

docs/deploy/11-gitops.md
workload/a0005-i/microservice-c/deployment.yaml
workload/a0005-i/web-frontend/deployment.yaml
workload/a0005-i/web-frontend/ingress.yaml
workload/a0005-o/microservice-a/deployment.yaml
workload/a0005-o/microservice-b/deployment.yaml

* Update PDBs to v1 from v1beta for 1.21
* Update the output that shows Kubernetes version numbers to 1.21 from 1.20
* Require HTTPS ingress now has another condition for nginx, added.

Fix PDB and new HTTPS Ingress Policy rule

---

cluster-manifests/kube-system/osm-config.yaml

* OSM is now configured via a custom CRD in 0.9.x, migrate to that CRD instead of ConfigMap

OSM: Switch from config map (0.8.x) to MeshConfig (0.9.x)

---

cluster-manifests/ingress-nginx/deployment.yaml
cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
cluster-stamp.json
cluster-stamp.v2.json

This PR does the following:
* Adds Prometheus metrics collection on the ingress controller
* Updates the Log Analytics query that used to be pulling Traefik metrics. This Fixes #26.
* Remove old `osm-system` namespace (from pre-addon days) from OMS agent config.
Tested as functioning.

Ingress Controller: Add Metrics & Update Query

---

cluster-stamp.json
cluster-stamp.v2.json
docs/deploy/01-prerequisites.md
docs/deploy/02-ca-certificates.md

* Paid SLA
* Better preview feature instructions
* Add SAN and key usage extensions to browser-facing cert

Port changes from Baseline

---

subscription.json

While we don't use them in this RI, the hub is designed to accept virtual network gateways (we have a subnet for them afterall).  Allowing it for a bit more realism.

Allow Virtual Network Gateways in the hub resource group

---

networking/hub-region.v0.json
networking/hub-region.v1.json
networking/hub-region.v2.json

1) Usage of  "categoryGroup": "allLogs" in Azure FW Diagnostic Settings
2) When running install-k8scli, "objects.githubusercontent.com" Fqdns should be allowed

AKS regulated - hubs Firewall fixes

---

README.md
cluster-manifests/ingress-nginx/akv-tls-provider.yaml
cluster-manifests/ingress-nginx/deployment.yaml
cluster-stamp.json
cluster-stamp.v2.json
docs/deploy/04-subscription.md
docs/deploy/10-pre-bootstrap.md
docs/deploy/11-gitops.md

* Update AKS to 1.22.4 (from 1.21.2)
* Move Azure Key Vault Secret Provider to non-alpha API version
* Better handling of NetworkWatcherRG naming
* Update to latest nginx (1.1.0) Pre-1.x versions are not compatible with 1.22

Update to 2.22.4

---

.gitignore
docs/deploy/06-aks-jumpboximage.md
jumpbox/jumpbox-bicep.txt

The Jumpbox image builder repo is switching to bicep, integrating that change into this readme.
No functional changes, just procedural ones.
This will go live in conjunction with mspnp/aks-jumpbox-imagebuilder#13.

Sync with Jump Box migration to Bicep

---

README.md
cluster-stamp.bicep
docs/deploy/09-pre-cluster-stamp.md
docs/deploy/11-validate-cluster-access-and-bootstrapping.md

closes: #23808
we want to bump the regulated AKS cluster to the latest GA(ed) version to keep our baselines up to date.
- bump AKS Version from 1.24 to 1.25
- additional hardening like upgrade to stable
- naming convention change for OMS to be aligned with latest changes and baseline.
- other minors
as a user you can clone and execute the document steps to deploy a new AKS cluster using the latest version.

feat (cluster): [upgrade version] cluster to the latest k8s supported version (v1.23 to v1.25)

---

docs/deploy/02-ca-certificates.md

Revert "bug fix - align cert env var name with cluster expected param"
This reverts commit e5cf4427a30fdbff522b69c32348a0f88206543a.

patch (deploy): [docs] revert ingress var name to its original shorter naming convention

---

cluster-manifests/cluster-baseline-settings/kured/kured.yaml
cluster-manifests/cluster-baseline-settings/kustomization.yaml
cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
docs/deploy/09-pre-cluster-stamp.md
docs/deploy/14-validation-logs.md

closes partially: #23809 
we want to keep every oss in-cluster up to date and align manifests with upstream in this case with baseline template.
- Updated kured to latest version (1.9.2 -> 1.12.0) and synced yaml manifests with upstream
- Updated Azure Monitor's configuration to be synced with upstream
clone the repo and follow the instructions. After provisioning the AKS regulated cluster it should be running kured 1.12.0 and azm configuration should be similar to the aks baseline. 
this has been tested e-2-e

feat (in-cluster infra): [upgrade oss] bump kured to 1.12.0 and azm cfg

---

cluster-manifests/ingress-nginx/deployment.yaml
docs/deploy/09-pre-cluster-stamp.md

closes partially: #23809 
we want to keep every oss in-cluster up to date and align manifests with upstream in this case with [nginx quickstart repo](https://github.com/kubernetes/ingress-nginx/blob/a00cf624b7ef43f44278bf1ce1114e0de663104e/docs/deploy/index.md#quick-start).
- Updated nginx to latest version (1.1.2 -> 1.5.1) and synced yaml manifests with upstream
- minor bug fix 8d0c3442256f767ab0fac582d87e3ac91b30fe07 from #66
clone the repo and follow the instructions. After provisioning the AKS regulated cluster it should be running nginx 1.5.1. 
Tested e2e:

feat (in-cluster infra): [upgrade oss] bump nginx to 1.5.1

---

cluster-manifests/falco-system/clusterrole.yaml
cluster-manifests/falco-system/clusterrolebinding.yaml
cluster-manifests/falco-system/configmap.yaml
cluster-manifests/falco-system/daemonset.yaml
cluster-manifests/falco-system/kustomization.yaml
cluster-manifests/falco-system/limit-range.yaml
cluster-manifests/falco-system/resource-quota.yaml
cluster-manifests/falco-system/serviceaccount.yaml
docs/deploy/09-pre-cluster-stamp.md
networking/hub-region.v2.bicep

closes partially: #23809 
we want to keep every oss in-cluster up to date and align manifests with upstream in this case with [falco template repo](https://github.com/falcosecurity/deploy-kubernetes/tree/0faf1e702b4f4508414d9b14d178670d782ce25d/kubernetes/falco/templates).
- Updated falco to latest version (0.29.1 -> 0.33.1) and synced yaml manifests with upstream
clone the repo and follow the instructions. After provisioning the AKS regulated cluster it should be running flaco 0.33.1. 
tested e2e

feat (in-cluster infra): [upgrade oss] bump falco to 0.33.1

---

README.md
cluster-stamp.bicep
docs/deploy/11-validate-cluster-access-and-bootstrapping.md

closes: #23808
We want to keep our AKS clusters version fresh upgrading to latest and testing it in our regulated one.
- bumped kubernetes version to `1.26`
You can clone and follow the steps to deploy the cluster and all works as expected and cluster version is `1.26`

feat (cluster): [version] bump aks regulater cluster to 1.26

---

README.md
cluster-stamp.bicep
docs/deploy/01-prerequisites.md

1- Aks version
2- Workload identity is not on preview any more
3- az cli version

Updates First pass

---

cluster-stamp.bicep

- [bug fix: add secure decorator to x509 private keys](https://github.com/mspnp/aks-baseline-regulated/commit/d3d89c33104e0cfd8312e30a631e7610c7d5816a)

patch (security): [deployment] add secure decorator to x509 private keys

---

cluster-stamp.bicep
docs/deploy/04-subscription.md
docs/deploy/05-networking-hub.md
docs/deploy/06-aks-jumpboximage.md
docs/deploy/08-cluster-networking.md
docs/deploy/09-pre-cluster-stamp.md
docs/deploy/10-aks-cluster.md
docs/deploy/11-validate-cluster-access-and-bootstrapping.md
docs/deploy/15-cleanup.md
modules/ensureClusterIdentityHasRbacToSelfManagedResources.bicep
networking/hub-region.v0.bicep
networking/hub-region.v1.bicep
networking/hub-region.v2.bicep
networking/spoke-BU0001A0005-00.bicep
networking/spoke-BU0001A0005-01.bicep
pre-cluster-stamp.bicep
subscription.bicep

- modify resource group creation to make the location part of the resource group's name
- modify network and cluster biceps to convert the location param to a variable defaulting to the rg location
- modify steps to use new naming convention and remove location argument

feat (deployment): [rgs] follow the region resource recommendations

---

cluster-manifests/kube-system/ama-metrics-prometheus-config-configmap.yaml
cluster-manifests/kube-system/ama-metrics-prometheus-config-node-configmap.yaml
cluster-manifests/kube-system/ama-metrics-settings-configmap.yaml
cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
cluster-stamp.bicep
modules/workloadPoliciesDeployment.bicep
networking/hub-region.v2.bicep

- enable networking observability (basic)
- add az monitor workspace
- create collection ep with az monitor ws as destination with cluster collection scope
- add default configmaps for ama-metrics agent

feat (deploy): [cluster] enable networking observability (basic)

---

cluster-manifests/ingress-nginx/deployment.yaml
docs/deploy/09-pre-cluster-stamp.md
docs/deploy/13-validation.md

Moving to k8s 1.30 enables the possibility of upgrading to newer nginx versions
- Cluster manifest files | based on https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.3/deploy/static/provider/cloud/deploy.yaml
- Doc deployment files
- Bug fix: add location to rg from e2e validation section

feat (in-cluster): [ingress-controller] update nginx to v1.11.3
