mspnp/aks-baseline-regulated

README.md
docs/deploy/01-prerequisites.md
docs/deploy/03-aad.md
docs/deploy/04-subscription.md

Neil has performed a review and left me some feedback to consider addressing. I've applied quite a few of his suggestions here.

Apply CD Feedback

---

docs/deploy/04-subscription.md
docs/deploy/05-networking-hub.md

Signed-off-by: Chad Kittel <chad.kittel@gmail.com>

Minor typos

---

cluster-stamp.json
cluster-stamp.v2.json
docs/deploy/04-subscription.md
docs/deploy/05-networking-hub.md
docs/deploy/06-aks-jumpboximage.md
docs/deploy/10-pre-bootstrap.md

* Update AKS to 1.20.5
* Couple minor typos in the narative

Update to 1.20.5

---

cluster-stamp.json
cluster-stamp.v2.json

AzureAppGatewayAnalytics is deprecated and it avoid sucess deployment

Deleting AzureAppGatewayAnalytics

---

docs/deploy/11-gitops.md
networking/hub-region.v1.json
networking/hub-region.v2.json

Flux changed their URL structure, updating to reflect that.  This includes the firewall rule for the flux cli download.

Update flux URLs

---

cluster-manifests/README.md

Update OSM link

---

cluster-manifests/ingress-nginx/deployment.yaml
docs/deploy/10-pre-bootstrap.md

* Update to latest (non v1) version of nginx ingress controller.
Tested functioning.

Update nginx ingress controller from 0.44 to 0.49

---

cluster-manifests/falco-system/configmap.yaml
cluster-manifests/falco-system/daemonset.yaml
cluster-manifests/falco-system/resource-quota.yaml
docs/deploy/10-pre-bootstrap.md

* Update to latest falco release
* Config map is now expanded (no longer a single string)
* Adjust limits to prevent DS from being killed (upstream is 1 core, so going part way there)
Tested functioning.

Update to latest Falco

---

docs/additional-considerations.md
docs/deploy/13-validation-logs.md

Azure -> Microsoft Sentinel

---

cluster-stamp.json
cluster-stamp.v2.json

AKS baseline regulated - microsoft.insights/scheduledqueryrules updated version to 2021-02-01

---

cluster-manifests/cluster-baseline-settings/kured/kured.yaml
docs/deploy/10-pre-bootstrap.md

Bumping kured from 1.6 to 1.9 ahead of the AKS 1.22 update.

Update to latest kured

---

docs/deploy/01-prerequisites.md

Remove three GA'd features from the pre-reqs list

Update previews to match GA'd features

---

cluster-stamp.bicep
cluster-stamp.v2.bicep

Adding output cluster name information needed
https://github.com/v-fearam/aks-baseline-regulated/blob/main/docs/deploy/11-gitops.md#steps -> step 7. 
AKS_CLUSTER_NAME=$(az deployment group show -g rg-bu0001a0005 -n cluster-stamp --query properties.outputs.aksClusterName.value -o tsv)

Adding cluster Information

---

cluster-manifests/ingress-nginx/deployment.yaml
docs/deploy/09-pre-cluster-stamp.md

just a continuation for #77 
tested e2e

feat (in-cluster infra): [upgrade oss] bump nginx to 1.6.4

---

cluster-stamp.bicep

Added missing defaults -- this way it's clearer what the syslog config is doing.

Add syslog defaults

---

cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml

https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml

container-azm-ms-agentconfig

---

cluster-manifests/ingress-nginx/deployment.yaml
cluster-manifests/ingress-nginx/kustomization.yaml
docs/deploy/09-pre-cluster-stamp.md

https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.0/deploy/static/provider/cloud/deploy.yaml

nginx 1.9.0

---

docs/deploy/09-pre-cluster-stamp.md

- update docs for run image audits from classic to the new experience
related: #308591

topic (docs): [security]  update to new recommendations experience

---

README.md
cluster-stamp.bicep
pre-cluster-stamp.bicep

This PR updates the version of AKS
- update deployment docs
- upgrade from aks version from 1.27.3 to 1.30
others:
- fix warnings in cluster-stamp

feat (deployment): [cluster] AKS v1.30 update

---

docs/deploy/07-aks-jumpbox-users.md
jumpBoxCloudInit.yml

- remove sensitive identifiers
- modify steps to ensure proper generation and assignment of the ssh public key

feat (deployment): [jumpbox] remove public key from cloud init file

---

cluster-manifests/cluster-baseline-settings/kustomization.yaml
docs/deploy/09-pre-cluster-stamp.md

we wanted to update busybox to the very latest version available
- manifest files for fim and av solution
- doc deployment steps, import and quarantine alert step

feat (in-cluster): [dmmy fim & av solution] update busybox to v1.37.0
